// Deploy the EvidenceArchive sidecar against an EXISTING, already-live core.
// This is the path used to add complete on-chain backup to a running deployment
// without redeploying core/gov/lens or resetting Supabase: the archive only reads
// the core's public hashes to verify what it stores.
//
//   CORE_ADDR=0x74B4… npx hardhat run scripts/deploy-archive.js --network bscMainnet
//
// (Falls back to VITE_CONSENSUS_ADDR if CORE_ADDR is unset.) After deploy, set
// VITE_CONTENT_ARCHIVE_ADDR (frontend) + CONTENT_ARCHIVE_ADDR (edge secret) and
// redeploy the indexer + frontend.
const hre = require("hardhat");
const fs = require("fs");
const path = require("path");
const { preflight } = require("./_preflight");

const VERIFY_ARGS_ARCHIVE = path.join(__dirname, "verify-args-archive.js");

async function main() {
  // Guards: chainId confirmation (mainnet) + STRIP_REVERTS on real networks.
  await preflight();

  const core = process.env.CORE_ADDR || process.env.VITE_CONSENSUS_ADDR;
  if (!core) throw new Error("CORE_ADDR (or VITE_CONSENSUS_ADDR) env required");
  const [deployer] = await hre.ethers.getSigners();
  console.log("Deploying EvidenceArchive as", deployer.address, "against core", core);

  const Archive = await hre.ethers.getContractFactory("EvidenceArchive");
  const archive = await Archive.deploy(core);
  await archive.waitForDeployment();
  const addr = await archive.getAddress();

  // Single source of truth for verify: persist the EXACT ctor arg (the core
  // address) so `hardhat verify --constructor-args` always matches.
  fs.writeFileSync(
    VERIFY_ARGS_ARCHIVE,
    "// GENERATED by deploy-archive.js — do not edit by hand.\n" +
    "// EvidenceArchive ctor arg: the live EvidenceConsensus core address.\n" +
    `module.exports = ${JSON.stringify([core], null, 2)};\n`,
  );
  console.log("Wrote", path.basename(VERIFY_ARGS_ARCHIVE));

  console.log("EvidenceArchive deployed to:", addr);
  console.log("Add to .env:  VITE_CONTENT_ARCHIVE_ADDR=" + addr);
  console.log("Set edge secret:  CONTENT_ARCHIVE_ADDR=" + addr);
  console.log("Deploy block:", await hre.ethers.provider.getBlockNumber());
  console.log(`Verify:  STRIP_REVERTS=1 npx hardhat verify --network ${hre.network.name} --constructor-args scripts/verify-args-archive.js ${addr}`);
}

main().catch(err => { console.error(err); process.exit(1); });
