// Resumable finish: the main deploy confirmed the core but was interrupted (RPC
// timeout) before some sidecars / the setGovernance wiring. This deploys the
// missing pieces against the existing core (CORE_ADDR) without re-deploying it.
// It is IDEMPOTENT: reuse already-deployed sidecars via GOV_ADDR/LENS_ADDR/
// ARCHIVE_ADDR, and never re-call the one-shot setGovernance on an already-wired
// core. Run with STRIP_REVERTS=1 to match verifiable bytecode.
const hre = require("hardhat");
const fs = require("fs");
const path = require("path");
const { preflight, MAINNET_CHAIN_ID } = require("./_preflight");

const ZERO = "0x0000000000000000000000000000000000000000";
const VERIFY_ARGS_ARCHIVE = path.join(__dirname, "verify-args-archive.js");

function writeArgsFile(filePath, header, value) {
  const body =
    "// GENERATED by finish-deploy.js — do not edit by hand.\n" +
    `// ${header}\n` +
    `module.exports = ${JSON.stringify(value, null, 2)};\n`;
  fs.writeFileSync(filePath, body);
  console.log("Wrote", path.basename(filePath));
}

async function main() {
  // Guards: chainId confirmation (mainnet) + STRIP_REVERTS on real networks.
  const chainId = await preflight();

  const core = process.env.CORE_ADDR;
  if (!core) throw new Error("CORE_ADDR env required");
  const [deployer] = await hre.ethers.getSigners();
  console.log("Finishing deploy as", deployer.address, "against core", core);

  // Clean compile so any redeployed sidecar matches the STRIP_REVERTS build.
  await hre.run("clean");
  await hre.run("compile");

  // PeerGovernance: reuse GOV_ADDR if provided, else deploy a fresh one.
  let govAddr, gov;
  if (process.env.GOV_ADDR) {
    govAddr = process.env.GOV_ADDR;
    gov = await hre.ethers.getContractAt("PeerGovernance", govAddr);
    console.log("Reusing PeerGovernance at:", govAddr);
  } else {
    const Gov = await hre.ethers.getContractFactory("PeerGovernance");
    gov = await Gov.deploy(core);
    await gov.waitForDeployment();
    govAddr = await gov.getAddress();
    console.log("PeerGovernance deployed to:", govAddr);
  }

  // Lens: reuse LENS_ADDR if provided, else deploy a fresh one.
  let lensAddr;
  if (process.env.LENS_ADDR) {
    lensAddr = process.env.LENS_ADDR;
    console.log("Reusing EvidenceConsensusLens at:", lensAddr);
  } else {
    const Lens = await hre.ethers.getContractFactory("EvidenceConsensusLens");
    const lens = await Lens.deploy(core, govAddr);
    await lens.waitForDeployment();
    lensAddr = await lens.getAddress();
    console.log("EvidenceConsensusLens deployed to:", lensAddr);
  }

  // One-shot wiring: only call setGovernance when the core is unwired. If it is
  // already wired to govAddr, skip (idempotent re-run); if wired to a DIFFERENT
  // gov, abort loudly — proceeding would either revert or mislead the operator.
  const Core = await hre.ethers.getContractAt("EvidenceConsensus", core);
  const existing = await Core.governance();
  if (existing !== ZERO) {
    if (existing.toLowerCase() === govAddr.toLowerCase()) {
      console.log("core.governance already wired ->", govAddr, "(skipping setGovernance)");
    } else {
      throw new Error(
        `core.governance is already set to ${existing}, which differs from the ` +
        `gov we are using (${govAddr}). The core is wired to a different governance ` +
        `contract — refusing to proceed. Set GOV_ADDR=${existing} to reuse it.`,
      );
    }
  } else {
    const tx = await Core.setGovernance(govAddr);
    // Extra confirmations on mainnet so the one-shot write is final.
    await (chainId === MAINNET_CHAIN_ID ? tx.wait(3) : tx.wait());
    // Verify the wiring landed.
    const wired = await Core.governance();
    if (wired.toLowerCase() !== govAddr.toLowerCase()) {
      throw new Error(`setGovernance failed: core.governance()=${wired}, expected ${govAddr}`);
    }
    console.log("Wired core.governance ->", govAddr);
  }

  // EvidenceArchive: reuse ARCHIVE_ADDR if provided, else deploy a fresh one.
  let archiveAddr;
  if (process.env.ARCHIVE_ADDR) {
    archiveAddr = process.env.ARCHIVE_ADDR;
    console.log("Reusing EvidenceArchive at:", archiveAddr);
  } else {
    const Archive = await hre.ethers.getContractFactory("EvidenceArchive");
    const archive = await Archive.deploy(core);
    await archive.waitForDeployment();
    archiveAddr = await archive.getAddress();
    console.log("EvidenceArchive deployed to:", archiveAddr);
  }

  // Persist the archive's verify args (single core ctor arg) to match deploy.
  writeArgsFile(
    VERIFY_ARGS_ARCHIVE,
    "EvidenceArchive ctor arg: the live EvidenceConsensus core address.",
    [core],
  );

  const deployBlock = await hre.ethers.provider.getBlockNumber();

  console.log("\n=== Frontend (.env / Netlify) ===");
  console.log("VITE_CONSENSUS_ADDR=" + core);
  console.log("VITE_CONSENSUS_GOVERNANCE_ADDR=" + govAddr);
  console.log("VITE_CONSENSUS_LENS_ADDR=" + lensAddr);
  console.log("VITE_CONTENT_ARCHIVE_ADDR=" + archiveAddr);
  console.log("VITE_DEPLOY_BLOCK=" + deployBlock);

  console.log("\n=== Supabase edge secrets ===");
  console.log("CONSENSUS_ADDR=" + core);
  console.log("GOVERNANCE_ADDR=" + govAddr);
  console.log("CONTENT_ARCHIVE_ADDR=" + archiveAddr);
  console.log("CONSENSUS_RPC_URL=<your BSC RPC URL>          (set/confirm)");
  console.log("CONSENSUS_CHAIN_ID=" + chainId.toString() + "                          (set/confirm)");
}

main().catch(err => { console.error(err); process.exit(1); });
